### PR TITLE
Configure codecov to show coverage

### LINKED ISSUE #78: Add codecov

### PR DESCRIPTION
**Pull request by alexdewar**
I've performed all the necessary configuration on codecov.io and in the repo settings, so that coverage info can be uploaded. This also means that the codecov app will notify us about missing coverage in PRs.

Summary:

- Configure codecov to only warn about missing coverage without making the CI fail
- Add a workflow to upload coverage
- Add a badge displaying coverage to readme (along with a couple of others)

Closes #78.

### CODE REVIEW

**Review by dalonsoa — APPROVED** [review]
Brilliant!

**Comment by alexdewar** [comment]
The markdown link checker is complaining that it can't find a config file... but I thought the config file was optional...?

**Comment by dalonsoa** [comment]
But tests and markdown checks are failing :(

**Comment by alexdewar** [comment]
Ok, the coverage upload is also failing so I'm converting this to draft for now. Sorry for the noise!

**Comment by alexdewar** [comment]
Ok, should work now!

**Review by cc-a — APPROVED** [review]
Good stuff. Just need to check what account have you set up codecov.io under? It should really be tied to a team account rather than a personal one.

**Comment by dalonsoa** [comment]
The access is given to a repo in an organisation, even if someone gives that access, so it is not linked to a specific account. I can see the following, for example. `pyrealm` has nothing to do with us.

image

**Comment by cc-a** [comment]
> The access is given to a repo in an organisation, even if someone gives that access, so it is not linked to a specific account. I can see the following, for example. `pyrealm` has nothing to do with us.

Huh. TIL.

**Pull request merged**
